### ISSUE TITLE
Missing update database

### ISSUE THREAD

**Issue by kuramajssken001** [WarheadCore/WarheadCore#105]
Many database table files are missing. The database you provided does not match warheadcore

auth:
account_ muted table structure is missing accountid  and active field.
world:
Missing string_ module database table.
Missing string_race database table.
Missing string_class database table.

creature scriptname Kargatum_Guild_Creature and nax_frostwyrm_lair not in database.

**LastCommit**: 4afb595ca291+

**Comment by Winfidonarleyan** [comment]
Hm, good catch. I'll fix it when I have time.
