### ISSUE TITLE
Наксрамас, лут сундука 4х всадников для героик режимов

### ISSUE THREAD

**Issue by Wowkasu** [WarheadCore/WarheadCore#151]
Добавить в скрипт спавна сундука после убийства всадников еще 2 режима героики.

![](https://cdn.discordapp.com/attachments/738660643959341096/776821295228780554/unknown.png)

в итоге должно быть всего 4 сундука для 4х режимов сложности.

181366 = 10 об
193426 = 25 об
6181336 = 10 гер
6193426 = 25гер

![](https://cdn.discordapp.com/attachments/738660643959341096/776820051365199942/unknown.png)

**Comment by Winfidonarleyan** [comment]
d69dc39
