### ISSUE TITLE
[BUG] Scripts/ICC: Blood Prince. Valanar

### ISSUE THREAD

**Issue by Wowkasu** [WarheadCore/WarheadCore#23]
Бос применяет две абилки:
Колдовское пламя https://wotlkdb.com/?spell=71718
Жаркое колдовское пламя https://wotlkdb.com/?spell=72040
в результате которых прокают:
https://wotlkdb.com/?spell=71719
https://wotlkdb.com/?spell=72041
которые в свою очередь сумонят нипов "сферы"
![2020-08-30_05-19-23](https://user-images.githubusercontent.com/68443208/92313543-18304a80-eff7-11ea-933a-5bfd7e180fdc.png)
https://wotlkdb.com/?npc=38332
https://wotlkdb.com/?npc=38451

Суть проблемы, данные шары выбирают цель рандомно включая танка, если в этот момент хилы хилят то у них генерируется трит от захила, вследствие чего они переключаются на хила и летят на него. но могут выбрать целью милика или танка и упасть в мили зоне шотая всех миликов включая танка.

как должно быть? шар выбирает цель в рдд зоне и летит к ней по своему пути разряжаться "брызгами" в игроков которые попадаются у него на пути (игроки на кого шар не летит, стараются попасть под его траекторию, тем самым разряжая шар чтобы он не шотнул все в округе после попадания в свою цель)

Условия которые должны выполняться но не выполняются. 
1. Целью не должны быть танки (персонажи которые в таргете у босов Талдарам id37973, Валанар id37970, Келесет id37972)в ядре есть функция "ноу танк" хз где Андрей показывал )))
2. Целью должен быть игрок из рдд зоны как минум от 15-20 ярдов. (если все игроки близко и на дистанции 15-20 никого нет, то самый дальний)
3. Выбранная шарами цель не должна измениться.  

Момент когда шар пролетел "правильно" в рдд зону, разряжаясь по пути
https://youtu.be/19j9pLgr0sU?t=115

Не правильное поведение, (в данном случае шар выбрал в цель танка, и не разрядившись уебал всех миликов
https://youtu.be/19j9pLgr0sU?t=129

**Comment by Viste** [comment]
Еще не проверено, поэтому пока открыто!

**Comment by Viste** [comment]
tested fix working close
