### ISSUE TITLE
Eluna module is not building in the repository

### ISSUE THREAD

**Issue by diluh** [WarheadCore/WarheadCore#3]
##### SMALL DESCRIPTION:

# - I tried to compile this repository with module [Eluna](https://github.com/azerothcore/mod-eluna-lua-engine) got several errors in building windows vs2017 

### I would be very grateful if you could correct it to build this repository with Eluna module

That branch looks better than azerothcore

##### STEPS TO REPRODUCE THE PROBLEM:

1.  Clone module [eluna ](https://github.com/azerothcore/mod-eluna-lua-engine) in the folder modules
2. try to compile and get the compilation errors
3. 

##### BRANCH(ES):

master

##### OPERATING SYSTEM:

Windows 10 Pro 

##### MODULES:

All modules of the repository

##### OTHER CUSTOMIZATIONS:

No

**Comment by Winfidonarleyan** [comment]
This module will not be supported
