### ISSUE TITLE
Бой с королем личем в ЦЛК

### ISSUE THREAD

**Issue by Wowkasu** [WarheadCore/WarheadCore#68]
Во время боя с Королем Личем (https://wotlkdb.com/?npc=36597) на танка применяется способность, которая не должна применяться именно к танку.
![2020-09-18_21-27-52](https://user-images.githubusercontent.com/68443208/93609453-16eb1e80-f9f6-11ea-8c0c-a0c9ea60d96b.png)

https://wotlkdb.com/?spell=72762 *Оскверняет землю под какой-либо из целей. Любой противник, попавший на оскверненный участок, получит урон от темной магии; сам участок при этом увеличится. Время действия – 30 с.*

Данная способность применяется на 2й и 3й фазе если не считать перефазы на "зиму" технически это 3я и 5я фазы.

Абилка должна применяться к любому игроку кроме цели боса т.е. танка (в нашем случае она применяется рандомно, включая танка.

**Comment by brussens** [comment]
@Wowkasu Осквернение должно кидаться на танка. Смотрим на ютубе актуал видосы. На МТ кидается.

**Comment by Wokwer** [comment]
> @Wowkasu Осквернение должно кидаться на танка. Смотрим на ютубе актуал видосы. На МТ кидается.

Тут хотелось бы ссылки на эти роки, дабы убедиться что перед осквернением, никто с танка агро не срывал, ибо в таком случае осквернение может прилететь на танка т.к. он не был целью Лича в этот момент. -такие ситуации набюдал лично несколько раз.

Но по логике и тактике Лича держут в центре площадки, а осквернение разливают по краям, после разлива, танк поворачивает Лича рожой на оскверненрие, а рейд становится босу заспину, из расчета, что Валькиры потащат игроков НЕ через лужу осквернения, По пути Валек раскидывают каток, ставят тотемы замедление и прочее, чтобы за время движения Валек до края, успеть их уничтожить.

И вот возникает вопрос, если осквернение будет на танке (В ЦЕНТРЕ) то сколько останется места для траектории Валькир?  особенно в тот момент таймингка, когда Осквернение кидается через секунду после Валек. В такие моменты распределяются станы по валькам.... разбегаются.... выливают осквернение.... и добивают Валек. Повторю вопрос, сколько времени останится на добивание валек, если оскваернение у нас посредине (кинуло на мейн танка) а длинна траектории Валек до края сократилась в 2 раза!!!! да блять это можно вывезти только в овергире и и под геру, и/или если в 1-2 вальках те классы которые могут сейвится (рывок, ТП, отскок) иначе это просто потеря игроков, я крайне не уверен что это было задуманно именно так, типа ну чтож ребятки вам не повезло что осквернение на мейне. (приверт от бизард)))

**Comment by Viste** [comment]
Так и шо пацаны откатывать или шо

**Comment by brussens** [comment]
@Wokwer братишка, я поищу, сами этот вопрос у себя поднимали. Нашли несколько видосов с офы - осквернение кидалось на мт. + знакомые задроты подтвердили это)

**Comment by brussens** [comment]
@Viste ну по сути https://youtu.be/TtPx2cjLCvg?t=305 вот вроде оно

**Comment by Viste** [comment]
ну ебана
